In [3]:
import pandas as pd

In [20]:
data={'Name':['Vishwa','Ram','Krishna','Ravi','Sam'],'Age':[19,20,21,22,23]}

In [21]:
d1=pd.DataFrame(data)
d1

      Name  Age
0   Vishwa   19
1      Ram   20
2  Krishna   21
3     Ravi   22
4      Sam   23

In [22]:
d1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
dtypes: int64(1), str(1)
memory usage: 212.0 bytes

In [23]:
d1.describe()

             Age
count   5.000000
mean   21.000000
std     1.581139
min    19.000000
25%    20.000000
50%    21.000000
75%    22.000000
max    23.000000

In [25]:
d1[d1['Age']>=21]

      Name  Age
2  Krishna   21
3     Ravi   22
4      Sam   23

In [26]:
import pandas as pd

In [32]:
lst=[['Alice',25],['Bob',30]]
df=pd.DataFrame(lst,columns=['Name','Age'])
df

    Name  Age
0  Alice   25
1    Bob   30

In [1]:
import pandas as pd

In [7]:
lst=[['Ram',25],['Ravi',30],['Alice', 25],['Bob', 30],['Arul', 26],['Mukesh', 40],['King',10], ['Elon', 38],['Alex',15], ['Bala', 19]]
df=pd.DataFrame(lst,columns=['Name','Age'])
df

     Name  Age
0     Ram   25
1    Ravi   30
2   Alice   25
3     Bob   30
4    Arul   26
5  Mukesh   40
6    King   10
7    Elon   38
8    Alex   15
9    Bala   19

In [8]:
df.head()  	
df.tail()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     str
 1   Age     10 non-null     int64
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

             Age
count  10.000000
mean   25.800000
std     9.425733
min    10.000000
25%    20.500000
50%    25.500000
75%    30.000000
max    40.000000

In [9]:
df[df['Age'] > 25]

     Name  Age
1    Ravi   30
3     Bob   30
4    Arul   26
5  Mukesh   40
7    Elon   38

In [12]:
df.isnull()
df.dropna()
df.fillna(0)

     Name  Age
0     Ram   25
1    Ravi   30
2   Alice   25
3     Bob   30
4    Arul   26
5  Mukesh   40
6    King   10
7    Elon   38
8    Alex   15
9    Bala   19

In [19]:
df.sort_values('Age')
df['Age'].apply(lambda x: x + 1)
df['Name'].unique()
df['Age'].value_counts()

Age
25    2
30    2
26    1
40    1
10    1
38    1
15    1
19    1
Name: count, dtype: int64

In [20]:
df.loc[0]

Name    Ram
Age      25
Name: 0, dtype: object

In [21]:
df.loc[1]

Name    Ravi
Age       30
Name: 1, dtype: object

In [22]:
df.iloc[1]

Name    Ravi
Age       30
Name: 1, dtype: object